package image

import (
	"bytes"
	"image/png"
	"os"
	"testing"
)

func TestGenerateCard(t *testing.T) {
	// Clean up font if downloaded during testing to verify download,
	// or we can just leave it to verify it behaves correctly when font exists.
	// We'll verify both states.
	err := EnsureFontDownloaded()
	if err != nil {
		t.Fatalf("EnsureFontDownloaded failed: %v", err)
	}

	// Verify font file exists
	if _, err := os.Stat("data/Inter-SemiBold.ttf"); err != nil {
		t.Fatalf("Font file not found after EnsureFontDownloaded: %v", err)
	}

	tests := []struct {
		category string
		title    string
		details  string
		source   string
	}{
		{
			category: "emergency",
			title:    "DARURAT: Peringatan Badai Cuaca Ekstrem Jabodetabek",
			details:  "Badan Meteorologi dan Geofisika mengeluarkan peringatan dini siaga banjir untuk seluruh wilayah Jakarta, Depok, Tangerang, dan Bekasi selama 24 jam ke depan.",
			source:   "BMKG",
		},
		{
			category: "market",
			title:    "Rupiah Jisdor Melemah Menjadi Rp 16.345 Per Dolar AS",
			details:  "Nilai tukar rupiah terhadap dolar AS berdasarkan kurs referensi Jakarta Interbank Spot Dollar Rate (JISDOR) kembali melemah seiring ketidakpastian pasar global.",
			source:   "Bank Indonesia",
		},
		{
			category: "crypto",
			title:    "Bitcoin Menembus Rekor Baru USD 98.500",
			details:  "Harga Bitcoin (BTC) melanjutkan reli positifnya hingga mencetak rekor tertinggi sepanjang sejarah (ATH) seiring meningkatnya adopsi institusional.",
			source:   "CoinMarketCap",
		},
		{
			category: "news",
			title:    "Pemerintah Resmi Menaikkan Tarif PPN Jadi 12% Mulai Tahun Depan",
			details:  "Kementerian Keuangan memastikan penyesuaian tarif Pajak Pertambahan Nilai (PPN) dari 11% menjadi 12% akan dimulai secara serentak di seluruh Indonesia.",
			source:   "CNBC Indonesia",
		},
		{
			category: "other",
			title:    "Info Harian Pasar Saham Gabungan",
			details:  "Indeks Harga Saham Gabungan (IHSG) hari ini ditutup menguat tipis seiring aksi beli bersih oleh investor asing pada saham-saham perbankan.",
			source:   "BEI",
		},
	}

	for _, tc := range tests {
		t.Run(tc.category, func(t *testing.T) {
			pngBytes, err := GenerateCard(tc.category, tc.title, tc.details, tc.source)
			if err != nil {
				t.Fatalf("GenerateCard failed: %v", err)
			}

			if len(pngBytes) == 0 {
				t.Fatal("GenerateCard returned empty slice")
			}

			// Validate that it's a valid PNG by decoding it
			img, err := png.Decode(bytes.NewReader(pngBytes))
			if err != nil {
				t.Fatalf("Failed to decode generated bytes as PNG: %v", err)
			}

			// Verify dimensions (1200x675)
			bounds := img.Bounds()
			if bounds.Dx() != 1200 || bounds.Dy() != 675 {
				t.Errorf("Expected dimensions 1200x675, got %dx%d", bounds.Dx(), bounds.Dy())
			}
		})
	}
}
